'use client';

import React from 'react';
import Navbar from '@/components/main/navbar';
import ShaderBackground from '@/components/main/shader-background';
import Link from 'next/link';
import { useAuth } from '@/context/AuthContext';
import { useRouter } from 'next/navigation';

export default function AuthContent() {
  const { user, signInWithGoogle, loading } = useAuth();
  const router = useRouter();
  const [error, setError] = React.useState<string | null>(null);

  React.useEffect(() => {
    if (!loading && user) {
      router.replace('/dashboard');
    }
  }, [user, loading, router]);

  const handleGoogleLogin = async () => {
    try {
      setError(null);
      await signInWithGoogle();
    } catch (err: any) {
      setError(err.message || '로그인 중 오류가 발생했습니다.');
      console.error('Login error:', err);
    }
  };

  if (loading || user) {
    return (
      <main>
        <ShaderBackground>
          <div style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            height: '100%',
            color: 'white',
            fontFamily: "'Space Grotesk', sans-serif",
          }}>
            <div style={{ textAlign: 'center' }}>
              <div style={{ 
                width: '40px', 
                height: '40px', 
                border: '3px solid rgba(255,255,255,0.1)', 
                borderTopColor: 'white', 
                borderRadius: '50%', 
                animation: 'spin 1s linear infinite',
                margin: '0 auto 1rem'
              }} />
              <p style={{ opacity: 0.6 }}>Authenticating...</p>
              <style>{`
                @keyframes spin {
                  to { transform: rotate(360deg); }
                }
              `}</style>
            </div>
          </div>
        </ShaderBackground>
      </main>
    );
  }

  return (
    <main style={{ height: '100vh', width: '100vw', overflow: 'hidden' }}>
      <ShaderBackground>
        <div style={{
          display: 'flex',
          height: '100%',
          width: '100%',
          fontFamily: "'Space Grotesk', sans-serif",
        }}>
          {/* Left Section (3/5) */}
          <div style={{
            flex: 3,
            backgroundColor: 'rgba(0, 0, 0, 0.4)',
            backdropFilter: 'blur(4px)',
            padding: '4rem',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'space-between',
            color: 'white',
            position: 'relative',
          }}>
            <div>
              <Link href="/" style={{ textDecoration: 'none', color: 'white' }}>
                <h2 style={{ fontSize: '1.5rem', fontWeight: 700 }}>ythumb AI</h2>
              </Link>
            </div>

            <div style={{ maxWidth: '600px' }}>
              <h1 style={{ 
                fontSize: '4.5rem', 
                fontWeight: 800, 
                lineHeight: 1.1, 
                marginBottom: '1.5rem',
                letterSpacing: '-0.04em'
              }}>
                Captivate Your Audience Instantly.
              </h1>
              <p style={{ 
                fontSize: '1.25rem', 
                color: 'rgba(255, 255, 255, 0.6', 
                lineHeight: 1.6 
              }}>
                Join the elite circle of creators using high-CTR thumbnails generated by advanced neural networks. Every pixel optimized for growth.
              </p>
            </div>

            {/* Oversized Footer Text */}
            <div style={{
              fontSize: '12vw',
              fontWeight: 900,
              color: 'rgba(255, 255, 255, 0.05)',
              lineHeight: 0.8,
              letterSpacing: '-0.05em',
              marginLeft: '-1rem',
              pointerEvents: 'none',
              userSelect: 'none',
            }}>
              ythumb
            </div>
          </div>

          {/* Right Section (2/5) */}
          <div style={{
            flex: 2,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '2rem',
          }}>
            <div style={{
              width: '100%',
              maxWidth: '420px',
              backgroundColor: 'rgba(255, 255, 255, 0.03)',
              backdropFilter: 'blur(32px) saturate(180%)',
              borderRadius: '32px',
              border: '1px solid rgba(255, 255, 255, 0.08)',
              padding: '3.5rem 2.5rem',
              textAlign: 'center',
              boxShadow: '0 50px 100px -20px rgba(0, 0, 0, 0.5)',
            }}>
              <h2 style={{
                fontSize: '2.25rem',
                fontWeight: 700,
                marginBottom: '1rem',
                color: 'white',
                letterSpacing: '-0.02em',
              }}>
                Welcome Back
              </h2>
              <p style={{
                fontSize: '1rem',
                color: 'rgba(255, 255, 255, 0.5)',
                marginBottom: '3rem',
                lineHeight: '1.5',
              }}>
                Ready to create your next viral hit? Let's get you signed in.
              </p>

              {error && (
                <div style={{ 
                  backgroundColor: 'rgba(255, 68, 68, 0.1)', 
                  border: '1px solid rgba(255, 68, 68, 0.2)',
                  borderRadius: '12px',
                  padding: '1rem',
                  marginBottom: '1.5rem',
                  color: '#ff4444', 
                  fontSize: '0.9rem' 
                }}>
                  {error}
                </div>
              )}

              {/* Google Login Button */}
              <button
                onClick={handleGoogleLogin}
                style={{
                  width: '100%',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  gap: '12px',
                  padding: '16px',
                  borderRadius: '14px',
                  backgroundColor: 'white',
                  color: '#000',
                  border: 'none',
                  fontSize: '1rem',
                  fontWeight: 600,
                  cursor: 'pointer',
                  transition: 'transform 0.2s, box-shadow 0.2s',
                  boxShadow: '0 10px 30px rgba(255, 255, 255, 0.1)',
                  fontFamily: 'inherit',
                }}
                onMouseEnter={(e: React.MouseEvent<HTMLButtonElement>) => {
                  const target = e.currentTarget;
                  target.style.transform = 'translateY(-2px)';
                  target.style.boxShadow = '0 15px 40px rgba(255, 255, 255, 0.15)';
                }}
                onMouseLeave={(e: React.MouseEvent<HTMLButtonElement>) => {
                  const target = e.currentTarget;
                  target.style.transform = 'translateY(0)';
                  target.style.boxShadow = '0 10px 30px rgba(255, 255, 255, 0.1)';
                }}
              >
                <GoogleIcon />
                Continue with Google
              </button>

              <div style={{
                marginTop: '3rem',
                fontSize: '0.85rem',
                color: 'rgba(255, 255, 255, 0.3)',
              }}>
                By continuing, you agree to our{' '}
                <Link href="/terms" style={{ color: 'rgba(255, 255, 255, 0.5)', textDecoration: 'none' }}>Terms</Link>
                {' '}and{' '}
                <Link href="/privacy" style={{ color: 'rgba(255, 255, 255, 0.5)', textDecoration: 'none' }}>Privacy Policy</Link>.
              </div>
            </div>
          </div>
        </div>
      </ShaderBackground>
    </main>
  );
}

function GoogleIcon() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24">
      <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"/>
      <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-1 .67-2.28 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/>
      <path d="M5.84 14.09c-.22-.67-.35-1.39-.35-2.09s.13-1.42.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l3.66-2.84z" fill="#FBBC05"/>
      <path d="M12 5.38c1.62 0 3.06.56 4.21 1.66l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/>
    </svg>
  );
}
